defmodule Helpdesk.Repo.Migrations.AddInAppNotifications do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:notifications, primary_key: false) do
      add :message_id,
          references(:messages, column: :id, name: "notifications_message_id_fkey", type: :uuid)

      add :ticket_id,
          references(:tickets, column: :id, name: "notifications_ticket_id_fkey", type: :uuid),
          null: false

      add :recipient_id,
          references(:users, column: :id, name: "notifications_recipient_id_fkey", type: :uuid),
          null: false

      add :outbox_event_id,
          references(:notification_outbox_events,
            column: :id,
            name: "notifications_outbox_event_id_fkey",
            type: :uuid
          ),
          null: false

      add :inserted_at, :utc_datetime_usec, null: false
      add :read_at, :utc_datetime_usec
      add :kind, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:notifications, ["recipient_id", "read_at"])

    create index(:notifications, ["recipient_id", "inserted_at", "id"])

    create unique_index(:notifications, [:outbox_event_id, :recipient_id],
             name: "notifications_unique_event_recipient_index"
           )
  end

  def down do
    drop_if_exists unique_index(:notifications, [:outbox_event_id, :recipient_id],
                     name: "notifications_unique_event_recipient_index"
                   )

    drop_if_exists index(:notifications, ["recipient_id", "inserted_at", "id"],
                     name: "notifications_recipient_id_inserted_at_id_index"
                   )

    drop_if_exists index(:notifications, ["recipient_id", "read_at"],
                     name: "notifications_recipient_id_read_at_index"
                   )

    drop table(:notifications)
  end
end
