defmodule Helpdesk.Repo.Migrations.AddStatusToUser do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :status, :text, null: false, default: "active"
    end
  end

  def down do
    alter table(:users) do
      remove :status
    end
  end
end
