defmodule Helpdesk.Repo.Migrations.AddTicketCreator do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tickets) do
      add :created_by_id,
          references(:users, column: :id, name: "tickets_created_by_id_fkey", type: :uuid)
    end
  end

  def down do
    alter table(:tickets) do
      remove :created_by_id
    end

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `tickets` table without the `tickets_created_by_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."
  end
end
