defmodule Helpdesk.Repo.Migrations.CreateKnowledgeBaseArticlesTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:knowledge_base_articles, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :published_at, :utc_datetime_usec
      add :published, :boolean, null: false
      add :position, :bigint, null: false
      add :featured, :boolean, null: false
      add :category, :text, null: false
      add :body, :text, null: false
      add :summary, :text, null: false
      add :slug, :text, null: false
      add :title, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:knowledge_base_articles, [:slug],
             name: "knowledge_base_articles_unique_slug_index"
           )
  end

  def down do
    drop_if_exists unique_index(:knowledge_base_articles, [:slug],
                     name: "knowledge_base_articles_unique_slug_index"
                   )

    drop table(:knowledge_base_articles)
  end
end
