defmodule Helpdesk.Repo.Migrations.AddFirstNameAndLastNameToUser do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :first_name, :text, null: false, default: "john"
      add :last_name, :text, null: false, default: "doe"
    end
  end

  def down do
    alter table(:users) do
      remove :last_name
      remove :first_name
    end
  end
end
