defmodule Helpdesk.Repo.Migrations.InitialSchema do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tickets, primary_key: false) do
      add :team_id, references(:teams, column: :id, name: "tickets_team_id_fkey", type: :uuid)
      add :reporter_id, :uuid
      add :assignee_id, :uuid
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :closed_at, :utc_datetime_usec
      add :resolved_at, :utc_datetime_usec
      add :due_at, :utc_datetime_usec
      add :category, :text
      add :source, :text, null: false
      add :priority, :text, null: false
      add :status, :text, null: false
      add :description, :text, null: false
      add :title, :text, null: false
      add :ticket_number, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:ticket_events, primary_key: false) do
      add :user_id, :uuid

      add :ticket_id,
          references(:tickets, column: :id, name: "ticket_events_ticket_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :metadata, :map
      add :new_value, :text
      add :old_value, :text
      add :field_name, :text
      add :event_type, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:teams, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :active, :boolean, null: false
      add :email, :citext
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:tickets, [:ticket_number], name: "tickets_unique_ticket_number_index")

    create unique_index(:teams, [:name], name: "teams_unique_name_index")

    create table(:team_memberships, primary_key: false) do
      add :team_id,
          references(:teams, column: :id, name: "team_memberships_team_id_fkey", type: :uuid)

      add :user_id, :uuid
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:messages, primary_key: false) do
      add :user_id, :uuid, null: false

      add :ticket_id,
          references(:tickets, column: :id, name: "messages_ticket_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :edited_at, :utc_datetime_usec
      add :external_message_id, :text
      add :source, :text, null: false
      add :message_type, :text, null: false
      add :body_format, :text
      add :body, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:audit_events, primary_key: false) do
      add :inserted_at, :utc_datetime_usec, null: false
      add :occurred_at, :utc_datetime_usec, null: false
      add :request_id, :text
      add :source, :text, null: false
      add :metadata, :map, null: false, default: %{}
      add :ticket_id, :uuid
      add :target_label, :text, null: false
      add :actor_label, :text, null: false
      add :actor_id, :uuid, null: false
      add :action, :text, null: false
      add :operation_id, :uuid, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:audit_events, [:operation_id],
             name: "audit_events_unique_operation_index"
           )

    create table(:attachments, primary_key: false) do
      add :message_id,
          references(:messages, column: :id, name: "attachments_message_id_fkey", type: :uuid)

      add :ticket_id,
          references(:tickets, column: :id, name: "attachments_ticket_id_fkey", type: :uuid)

      add :created_at, :utc_datetime_usec, null: false
      add :checksum, :text
      add :storage_key, :text, null: false
      add :byte_size, :bigint, null: false
      add :content_type, :text, null: false
      add :file_path, :text, null: false
      add :file_name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:attachments, [:storage_key],
             name: "attachments_unique_storage_key_index"
           )
  end

  def down do
    drop_if_exists unique_index(:attachments, [:storage_key],
                     name: "attachments_unique_storage_key_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `attachments` table without the `attachments_ticket_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `attachments` table without the `attachments_message_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:attachments)

    drop_if_exists unique_index(:audit_events, [:operation_id],
                     name: "audit_events_unique_operation_index"
                   )

    drop table(:audit_events)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `messages` table without the `messages_ticket_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:messages)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `team_memberships` table without the `team_memberships_team_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:team_memberships)

    drop_if_exists unique_index(:teams, [:name], name: "teams_unique_name_index")

    drop_if_exists unique_index(:tickets, [:ticket_number],
                     name: "tickets_unique_ticket_number_index"
                   )

    drop table(:teams)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `ticket_events` table without the `ticket_events_ticket_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:ticket_events)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `tickets` table without the `tickets_team_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:tickets)
  end
end
