defmodule Helpdesk.Repo.Migrations.AddNotificationOutbox do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:notification_outbox_events, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :last_error_code, :text
      add :processed_at, :utc_datetime_usec
      add :lease_expires_at, :utc_datetime_usec
      add :lease_token, :uuid
      add :next_attempt_at, :utc_datetime_usec, null: false
      add :attempts, :bigint, null: false
      add :status, :text, null: false
      add :occurred_at, :utc_datetime_usec, null: false
      add :schema_version, :bigint, null: false
      add :payload, :map, null: false, default: %{}
      add :candidate_recipient_ids, {:array, :uuid}, null: false, default: []
      add :kind, :text, null: false
      add :actor_id, :uuid
      add :message_id, :uuid
      add :ticket_id, :uuid, null: false
      add :source_event_id, :uuid, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:notification_outbox_events, ["status", "next_attempt_at"])

    create unique_index(:notification_outbox_events, [:source_event_id, :kind],
             name: "notification_outbox_events_unique_source_event_kind_index"
           )
  end

  def down do
    drop_if_exists unique_index(:notification_outbox_events, [:source_event_id, :kind],
                     name: "notification_outbox_events_unique_source_event_kind_index"
                   )

    drop_if_exists index(:notification_outbox_events, ["status", "next_attempt_at"],
                     name: "notification_outbox_events_status_next_attempt_at_index"
                   )

    drop table(:notification_outbox_events)
  end
end
