defmodule Helpdesk.Repo.Migrations.AddNotificationEmailDelivery do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:notification_preferences, primary_key: false) do
      add :user_id,
          references(:users,
            column: :id,
            name: "notification_preferences_user_id_fkey",
            type: :uuid
          ),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :email_enabled, :boolean, null: false
      add :kind, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:notification_preferences, [:user_id, :kind],
             name: "notification_preferences_unique_user_kind_index"
           )

    create table(:notification_deliveries, primary_key: false) do
      add :notification_id,
          references(:notifications,
            column: :id,
            name: "notification_deliveries_notification_id_fkey",
            type: :uuid
          ),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :provider_message_id, :text
      add :last_error_code, :text
      add :sent_at, :utc_datetime_usec
      add :lease_expires_at, :utc_datetime_usec
      add :lease_token, :uuid
      add :next_attempt_at, :utc_datetime_usec, null: false
      add :attempts, :bigint, null: false
      add :status, :text, null: false
      add :channel, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:notification_deliveries, ["status", "lease_expires_at"])

    create index(:notification_deliveries, ["status", "next_attempt_at"])

    create unique_index(:notification_deliveries, [:notification_id, :channel],
             name: "notification_deliveries_unique_notification_channel_index"
           )
  end

  def down do
    drop_if_exists unique_index(:notification_deliveries, [:notification_id, :channel],
                     name: "notification_deliveries_unique_notification_channel_index"
                   )

    drop_if_exists index(:notification_deliveries, ["status", "next_attempt_at"],
                     name: "notification_deliveries_status_next_attempt_at_index"
                   )

    drop_if_exists index(:notification_deliveries, ["status", "lease_expires_at"],
                     name: "notification_deliveries_status_lease_expires_at_index"
                   )

    drop table(:notification_deliveries)

    drop_if_exists unique_index(:notification_preferences, [:user_id, :kind],
                     name: "notification_preferences_unique_user_kind_index"
                   )

    drop table(:notification_preferences)
  end
end
